INSERT INTO public.inspiration (id,name,category) VALUES
	 (1,'A Forgotten Robot in a Flower Field','Robot'),
	 (2,'A Cozy Monster’s Bedroom','Monster'),
	 (3,'Ancient Tree with a Hidden Door','Tree'),
	 (4,'Portrait of a Character in Two Worlds','Duality'),
	 (5,'Tiny Creatures with Big Jobs','Miniature'),
	 (6,'Lonely Lighthouse at the Edge of the World','Landscape'),
	 (7,'A Cat Wearing a Detective Hat','Animal'),
	 (8,'Floating Islands Under a Pink Sky','Fantasy'),
	 (9,'A Clockmaker’s Secret Workshop','Steampunk'),
	 (10,'Two Rival Cities Split by a River','Duality'),
	 (11,'A Library Hidden Inside a Mountain','Architecture'),
	 (12,'Mechanical Butterflies in a Greenhouse','Robot'),
	 (13,'The Last Candle in an Endless Hall','Mystery'),
	 (14,'Ghostly Train Passing Through the Fog','Horror'),
	 (15,'A Mirror Showing a Different Past','Duality'),
	 (16,'A Child Holding a Galaxy in Their Hands','Sci-Fi'),
	 (17,'The Smallest Circus on Earth','Miniature'),
	 (18,'A Pirate Ship Sailing Through the Clouds','Adventure'),
	 (19,'Abandoned Carnival at Midnight','Horror'),
	 (20,'A Market Where Time Is Traded','Fantasy'),
	 (21,'The First Tree That Learned to Speak','Tree'),
	 (22,'A Garden Growing Crystals Instead of Flowers','Fantasy'),
	 (23,'A Secret Door Behind a Waterfall','Mystery'),
	 (24,'A City Powered by Giant Crystals','Sci-Fi'),
	 (25,'Lost Letters from the Future','Mystery'),
	 (26,'A Sky Full of Lanterns Over an Ancient Town','Festival'),
	 (27,'Tiny Robots Fixing a Giant Clock','Miniature'),
	 (28,'The Last Page of a Never-Ending Book','Mystery'),
	 (29,'A Lighthouse Floating in Space','Sci-Fi'),
	 (30,'A Hidden Village Inside a Giant Shell','Miniature'),
	 (31,'Portrait of a Wolf Wearing a Crown','Animal'),
	 (32,'A Forest with Glowing Blue Trees','Fantasy'),
	 (33,'A Train Station Where It’s Always Sunset','Landscape'),
	 (34,'A Robot Learning to Paint','Robot'),
	 (35,'A Bridge Made of Starlight','Fantasy'),
	 (36,'A Tea Party with Talking Animals','Whimsy'),
	 (37,'An Old Shipwreck Full of Ghosts','Horror'),
	 (38,'A Tower That Grows Taller Each Night','Mystery'),
	 (39,'A City Where People Ride Giant Birds','Fantasy'),
	 (40,'Portrait of a Queen with Mechanical Wings','Steampunk'),
	 (41,'A Garden Kept Alive by Singing','Fantasy'),
	 (42,'A Forgotten Library in the Clouds','Architecture'),
	 (43,'A Clock Tower That Controls the Seasons','Fantasy'),
	 (44,'Tiny Fairies Building a Snowman','Miniature'),
	 (45,'A Hidden Café That Only Appears in Dreams','Whimsy'),
	 (46,'A Monster Who Collects Stars','Monster'),
	 (47,'A Desert with Floating Stones','Landscape'),
	 (48,'A Mirror That Swaps Your Shadow','Mystery'),
	 (49,'A Train That Travels Backwards Through Time','Sci-Fi'),
	 (50,'A City Built on the Back of a Giant Turtle','Fantasy'),
	 (51,'The Last Robot in an Overgrown Garden','Robot'),
	 (52,'A Hidden Alleyway Leading to Another World','Mystery'),
	 (53,'A Fox Wearing a Samurai Helmet','Animal'),
	 (54,'A Bridge Covered in Endless Lanterns','Festival'),
	 (55,'A Castle Suspended by Balloons','Fantasy'),
	 (56,'A Market Run Entirely by Cats','Animal'),
	 (57,'A Tower Built from Musical Instruments','Whimsy'),
	 (58,'A Field of Umbrellas Instead of Flowers','Whimsy'),
	 (59,'A Giant Tree with a City in Its Branches','Tree'),
	 (60,'A Circus Train That Never Stops','Adventure'),
	 (61,'A Forgotten Door at the End of the Ocean','Mystery'),
	 (62,'A Garden Where the Flowers Glow at Night','Fantasy'),
	 (63,'A Village Made of Ice Cream','Whimsy'),
	 (64,'Tiny Dragons Living in Teacups','Miniature'),
	 (65,'A Haunted Library Where Books Whisper','Horror'),
	 (66,'A Robot Who Writes Poetry','Robot'),
	 (67,'A Hidden Shrine Inside a Volcano','Architecture'),
	 (68,'A Cloud That Rains Candy','Whimsy'),
	 (69,'A Lighthouse Surrounded by Floating Islands','Landscape'),
	 (70,'A Train Station in the Middle of Nowhere','Mystery'),
	 (71,'A Castle That Changes Shape Each Morning','Fantasy'),
	 (72,'An Owl Wearing Glasses and Reading a Book','Animal'),
	 (73,'A Market That Only Opens During Full Moons','Mystery'),
	 (74,'A Bridge That Appears Only at Midnight','Fantasy'),
	 (75,'A Ship Sailing Through a Sea of Stars','Adventure'),
	 (76,'A House Built from Giant Mushrooms','Fantasy'),
	 (77,'A Robot Guarding a Forgotten Temple','Robot'),
	 (78,'A Mirror Showing Your Alternate Self','Duality'),
	 (79,'A Tree That Grows Paper Leaves','Tree'),
	 (80,'A Library Where Each Book Is a Universe','Fantasy'),
	 (81,'A Cat Sleeping on a Floating Leaf','Animal'),
	 (82,'Tiny Villagers Living Inside a Clock','Miniature'),
	 (83,'A City Covered in Eternal Snow','Landscape'),
	 (84,'A Lighthouse That Signals Other Dimensions','Sci-Fi'),
	 (85,'A Garden Full of Singing Statues','Fantasy'),
	 (86,'A Train Powered by Dreams','Whimsy'),
	 (87,'A Fox with Golden Wings','Animal'),
	 (88,'A Mountain with a Hidden Observatory','Architecture'),
	 (89,'A Café That Serves Memories Instead of Food','Mystery'),
	 (90,'A Ship Made Entirely of Glass','Adventure'),
	 (91,'A Street Where It Always Rains','Landscape'),
	 (92,'Tiny Robots Fixing Broken Stars','Miniature'),
	 (93,'A Monster Who Sings to the Moon','Monster'),
	 (94,'A Bridge Between the Living and the Dead','Duality'),
	 (95,'A Village Hidden Inside a Giant Pumpkin','Whimsy'),
	 (96,'A Forest Where Leaves Turn Into Butterflies','Fantasy'),
	 (97,'A Forgotten Puppet Theater in the Woods','Horror'),
	 (98,'A Tower Where Every Floor Is a Different Season','Fantasy'),
	 (99,'A Cat Who Paints the Sky','Animal'),
	 (100,'A Mirror That Remembers Your Past Lives','Mystery'),
	 (101,'A Robot Learning to Dance','Robot'),
	 (102,'A Tree That Grows Lanterns','Tree'),
	 (103,'Tiny Monsters Having a Picnic','Miniature'),
	 (104,'A Library Hidden Beneath the Sea','Architecture'),
	 (105,'A City Made of Sandcastles','Whimsy');
