name: Deploy Docker Image
on: workflow_dispatch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: Build and deploy server
    if: github.ref_name == 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: "1"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_TOKEN_USERNAME }}
          password: ${{ secrets.ACR_TOKEN_PASSWORD }}
      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_REGISTRY }}/creative-companion:latest
          file: build.dockerfile
